from pathlib import Path

VERSION_NEW = "2026-06-25-platform-lock-display-v1"


def main():
    app = Path(__file__).resolve().parent / "app.py"
    if not app.exists():
        return
    text = app.read_text(encoding="utf-8")
    changed = False

    for old in [
        "2026-06-23-direct-ical-sync-v1",
        "2026-06-23-room-boot-light-v1",
        "2026-06-23-ical-loop-guard-v1",
        "2026-06-23-ical-no-external-locks-v1",
        "2026-06-24-room-entry-click-v1",
        "2026-06-24-sync-direct-v1",
        "2026-06-24-firestore-shard-history-v1",
    ]:
        old_text = f'PMS_PATCH_VERSION = "{old}"'
        new_text = f'PMS_PATCH_VERSION = "{VERSION_NEW}"'
        if old_text in text:
            text = text.replace(old_text, new_text, 1)
            changed = True
            break

    old_external_keys = '''_PMS_EXTERNAL_STATE_KEYS = ("icalEventArchive", "mailEvents")'''
    new_external_keys = '''_PMS_EXTERNAL_STATE_KEYS = ("icalEventArchive", "mailEvents", "icalSyncHistory")'''
    if old_external_keys in text:
        text = text.replace(old_external_keys, new_external_keys, 1)
        changed = True

    # Show platform-side Airbnb manual blocks in PMS again. The feed exporter below
    # skips imported iCal locks, so visible platform locks won't be sent back to Airbnb.
    old_skip_lock = '''        lock_reason = ical_lock_reason(summary, description, status)
        if lock_reason:
            continue
        stable_id = hashlib.sha1((str(listing_id) + "|" + uid).encode("utf-8")).hexdigest()[:24]'''
    new_show_lock = '''        lock_reason = ical_lock_reason(summary, description, status)
        stable_id = hashlib.sha1((str(listing_id) + "|" + uid).encode("utf-8")).hexdigest()[:24]'''
    if old_skip_lock in text:
        text = text.replace(old_skip_lock, new_show_lock, 1)
        changed = True

    old_orphan_hook = '''    listing_ids = {item.get("id") for item in listings if item.get("id")}
    previous_counts = {}
'''
    new_orphan_cleanup = '''    listing_ids = {item.get("id") for item in listings if item.get("id")}
    state["bookings"] = [
        booking for booking in state.get("bookings", [])
        if not (
            isinstance(booking, dict)
            and booking.get("source") == "ical"
            and booking.get("room_id") in allowed_room_ids
            and booking.get("channel_listing_id")
            and booking.get("channel_listing_id") not in listing_ids
        )
    ]
    previous_counts = {}
'''
    if old_orphan_hook in text and "channel_listing_id\") not in listing_ids" not in text:
        text = text.replace(old_orphan_hook, new_orphan_cleanup, 1)
        changed = True

    old_feed_guard = '''        if target_channel_id and booking.get("channel_listing_id") == target_channel_id:
            continue
        checkin = booking.get("checkin")'''
    new_feed_guard = '''        if target_channel_id and booking.get("channel_listing_id") == target_channel_id:
            continue
        imported_lock = booking.get("source") == "ical" and (booking.get("is_locked") or booking.get("booking_type") == "lock")
        marker_text = " ".join([
            str(booking.get("external_event_uid") or ""),
            str(booking.get("summary") or ""),
            str(booking.get("lock_reason") or ""),
            str(booking.get("status") or ""),
        ]).lower()
        if imported_lock or "@pms-system" in marker_text or "generated by pms anti-overbooking feed" in marker_text:
            continue
        checkin = booking.get("checkin")'''
    if old_feed_guard in text:
        text = text.replace(old_feed_guard, new_feed_guard, 1)
        changed = True

    if changed:
        app.write_text(text, encoding="utf-8")
        print("patched platform lock display")
    else:
        print("platform lock display patch already applied")


if __name__ == "__main__":
    main()
