var selectedPropertyId = '';
var expandedPlatformFields = {};
var expandedPublicRooms = {};
var editingPropertyNames = {};
var originalRenderOwnerForPms = window.renderOwner;

function pmsEsc(v){return String(v||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function pmsSafeId(v){return String(v||'').replace(/[^a-zA-Z0-9_-]/g,'_');}
function pmsCurrentGroupId(){return (groups[0]&&groups[0].id)||'group_default';}
function pmsKey(v){return String(v||'').trim().replace(/\s+/g,'').toLowerCase();}
function isAdminUser(){return !!(currentUser&&currentUser.role==='admin');}
function propRooms(propertyId){const f=(properties[0]&&properties[0].id)||'property_default';return rooms.filter(r=>(r.property_id||f)===propertyId);}
function propCommonAreas(propertyId){const f=(properties[0]&&properties[0].id)||'property_default';return commonAreas.filter(a=>(a.property_id||f)===propertyId);}
function activeProperty(){return selectedPropertyId ? (properties.find(p=>p.id===selectedPropertyId)||null) : null;}
function propertyNameInputId(id){return 'propertyName_'+pmsSafeId(id);}
function propertyDisplayName(p){return String((p&&(p.name||p.id))||'房源').trim();}
function propertyRoomTitleHtml(p){return `<span class="property-room-name">${pmsEsc(propertyDisplayName(p))}</span><span class="property-room-title-text">房间管理</span>`;}
function propertyCleanerBindings(propertyId){return propertyCleaners.filter(x=>x.property_id===propertyId);}
function normalizeCleanerCodeClient(v){let c=String(v||'').replace(/[^a-zA-Z0-9]/g,'').toUpperCase();if(c.startsWith('CLN'))c=c.slice(3);return c?'CLN-'+c:'';}
function cleanerLabel(code){const n=normalizeCleanerCodeClient(code);const u=(users||[]).find(x=>normalizeCleanerCodeClient(x.cleaner_code)===n);return u?`${u.name||'保洁'}（${n}）`:n;}

function updatePmsHeaderIdentity(){
  const title=document.querySelector('header h1');
  const sub=document.querySelector('header h1 + .small');
  if(getRoleFromPath&&getRoleFromPath()==='cleaner'){if(title)title.textContent='保洁查看页面';document.title='保洁查看页面';return;}
  const text=isAdminUser()?'PMS 系统管理员后台':`${(currentUser&&(currentUser.name||currentUser.username))||'房东'} · ${(currentUser&&currentUser.role)||'owner'}的PMS管理后台`;
  if(title)title.textContent=text;
  if(sub)sub.textContent=isAdminUser()?'查看房东账号、保洁账号、房源、房间、公区和绑定关系。':'管理房源、房间、公区、iCal 同步和保洁绑定。';
  document.title=text;
}
function renderAccountBar(){const nav=document.querySelector('.nav');if(!nav)return;nav.querySelectorAll('span.small').forEach(e=>e.remove());if(!document.getElementById('logoutBtn')){const b=document.createElement('button');b.id='logoutBtn';b.textContent='退出登录';b.onclick=logout;nav.appendChild(b);}updatePmsHeaderIdentity();}

function setupPropertyRoomUi(){
  const tab=document.querySelector('button[onclick*="ownerRooms"]');
  if(tab){tab.textContent='房源 / 房间设置';tab.setAttribute('onclick',"showOwnerTab('ownerRooms', this); backToPropertyList();");}
  const section=document.getElementById('ownerRooms');
  if(section){const h2=section.querySelector(':scope > .card h2');const p=section.querySelector(':scope > .card p.small');const sel=activeProperty();if(h2){h2.textContent=sel?'':'房源管理';h2.style.display=sel?'none':'';}if(p){p.textContent=sel?'':'先看到所有房源。可以添加、重命名、删除房源；点进入后再设置这个房源下面的房间和公区。';p.style.display=sel?'none':'';}section.querySelectorAll(':scope > .card > button[onclick="addRoom()"], :scope > .card > .toolbar').forEach(e=>e.style.display='none');}
  const commonHolder=document.getElementById('commonSettings');if(commonHolder){const c=commonHolder.closest('.card');if(c)c.style.display='none';}
  if(!document.getElementById('propertyRoomUiStyles')){const s=document.createElement('style');s.id='propertyRoomUiStyles';s.textContent=`.property-list-page{display:grid;gap:12px}.property-list-head,.property-detail-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.property-cards{display:grid;gap:10px}.property-card-row,.property-subcard,.admin-panel{border:1px solid var(--line);border-radius:8px;background:#fff;padding:14px}.property-card-row{display:grid;grid-template-columns:minmax(220px,1fr) auto;align-items:end}.property-card-actions,.property-actions,.platform-buttons,.room-compact-actions,.admin-relation-tags{display:flex;gap:8px;flex-wrap:wrap}.property-title-line{font-size:18px;font-weight:900;margin-bottom:8px}.property-meta-line,.common-save-status{color:var(--muted);font-size:13px}.property-room-shell,.common-area-list,.admin-shell,.admin-group-grid{display:grid;gap:12px}.property-room-title{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap;margin:0}.property-room-name{font-size:30px;line-height:1.1;font-weight:900;color:var(--primary)}.property-room-title-text{font-size:22px;font-weight:900;color:var(--text)}.common-area-card,.room-compact-head{display:grid;grid-template-columns:minmax(160px,1fr) 120px auto;gap:8px;align-items:end;border:1px solid var(--line);border-radius:8px;background:#f8fafc;padding:10px}.room-setting-card{border:1px solid var(--line);border-radius:8px;background:#fff;padding:12px;margin:10px 0}.room-ical-primary{display:grid;grid-template-columns:140px minmax(0,1fr);gap:8px;margin-top:10px}.optional-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:8px;margin-top:8px}.optional-box,.empty-panel{border:1px dashed var(--line);border-radius:8px;background:#f8fafc;padding:12px}.empty-panel{text-align:center;color:var(--muted)}.oversell-warning{border:1px solid #f59e0b;background:#fffbeb;border-radius:8px;padding:10px;margin-top:10px;color:#92400e}.admin-metric-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.admin-metric{border:1px solid var(--line);border-radius:8px;background:#fff;padding:12px}.admin-metric .num{font-size:28px;font-weight:900;color:var(--primary)}.admin-table{width:100%;border-collapse:collapse}.admin-table th,.admin-table td{padding:9px 10px;border-bottom:1px solid var(--line);text-align:left}@media(max-width:900px){.property-card-row,.common-area-card,.room-compact-head,.room-ical-primary{grid-template-columns:1fr}}`;document.head.appendChild(s);}
}

function openPropertyRooms(propertyId){selectedPropertyId=String(propertyId||'');renderRoomSettings();}
function backToPropertyList(){selectedPropertyId='';renderRoomSettings();}
function editPropertyName(id){editingPropertyNames[id]=true;renderRoomSettings();}
function cancelPropertyNameEdit(id){editingPropertyNames[id]=false;renderRoomSettings();}

async function savePropertyName(id,btn){const p=properties.find(x=>x.id===id);if(!p){alert('找不到这个房源');return null;}const input=document.getElementById(propertyNameInputId(id));const name=input?(input.value.trim()||p.name||'未命名房源'):(p.name||'未命名房源');const dup=properties.some(x=>x.id!==id&&(x.group_id||pmsCurrentGroupId())===(p.group_id||pmsCurrentGroupId())&&pmsKey(x.name)===pmsKey(name));if(dup){alert('房源名字不能重复，请换一个名字。');return null;}p.name=name;const old=btn?btn.textContent:'';if(btn){btn.disabled=true;btn.textContent='保存中...';}try{const r=await fetch(withKey('/api/property/'+encodeURIComponent(id)),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.error||'save property failed');applyServerState(d.state||d);editingPropertyNames[id]=false;renderCleaner();pmsRenderOwner();applyRoleMode();renderAccountBar();return d;}catch(e){alert('保存房源名字失败：'+e.message);return null;}finally{if(btn){btn.disabled=false;btn.textContent=old||'保存名字';}}}
function addProperty(){const p={id:'property'+Date.now(),group_id:pmsCurrentGroupId(),name:'新房源'};let i=2;while(properties.some(x=>pmsKey(x.name)===pmsKey(p.name))){p.name='新房源 '+i++;}properties.push(p);selectedPropertyId='';renderRoomSettings();savePropertyName(p.id,null).then(d=>{if(d){applyServerState(d.state||d);renderRoomSettings();}});}
async function deletePropertyUi(id,btn){const p=properties.find(x=>x.id===id);if(!p)return alert('找不到这个房源');if(properties.length<=1)return alert('不能删除最后一个房源。');if(!confirm(`确定删除房源「${p.name||id}」？`))return;const old=btn?btn.textContent:'';if(btn){btn.disabled=true;btn.textContent='删除中...';}try{properties=properties.filter(x=>x.id!==id);propertyCleaners=propertyCleaners.filter(x=>x.property_id!==id);commonAreas=commonAreas.filter(x=>(x.property_id||id)!==id);const ids=new Set(propRooms(id).map(r=>r.id));rooms=rooms.filter(r=>(r.property_id||id)!==id);bookings=bookings.filter(b=>!ids.has(b.room_id));await saveState();await loadState();selectedPropertyId='';renderCleaner();pmsRenderOwner();applyRoleMode();renderAccountBar();}catch(e){alert('删除房源失败：'+e.message);}finally{if(btn){btn.disabled=false;btn.textContent=old||'删除房源';}}}

function updateRoomField(id,field,value){const r=rooms.find(x=>x.id===id);if(!r)return;r[field]=field==='cleaning_fee'?Number(value||0):value;markRoomDirty(id);}
function showPlatformField(id,field){expandedPlatformFields[id+':'+field]=true;renderRoomSettings();}
function togglePublicLinks(id){expandedPublicRooms[id]=!expandedPublicRooms[id];renderRoomSettings();}
function hasOtherPlatformIcal(r){return !!(r.booking_ical||r.vrbo_ical||r.other_ical);}
function optionalPlatformRows(r){const fs=[['booking_ical','Booking'],['vrbo_ical','Vrbo'],['other_ical','其他平台']];const visible=fs.filter(([f])=>r[f]||expandedPlatformFields[r.id+':'+f]);const btns=fs.filter(([f])=>!r[f]&&!expandedPlatformFields[r.id+':'+f]).map(([f,l])=>`<button class="smallbtn" onclick="showPlatformField('${pmsEsc(r.id)}','${f}')">增加 ${l} iCal</button>`).join('');return `${btns?`<div class="platform-buttons">${btns}</div>`:''}${visible.length?`<div class="optional-grid">${visible.map(([f,l])=>`<div class="optional-box"><div class="ical-label">${l} iCal 导出链接</div><input class="ical-input" value="${pmsEsc(r[f]||'')}" onchange="updateRoomField('${pmsEsc(r.id)}','${f}',this.value)"></div>`).join('')}</div>`:''}`;}
function publicLinksPanel(r){return `<div class="platform-buttons"><button class="smallbtn" onclick="togglePublicLinks('${pmsEsc(r.id)}')">${expandedPublicRooms[r.id]?'收起公开链接':'公开房源链接（可选）'}</button></div>`;}
function oversellWarning(r){if(!hasOtherPlatformIcal(r))return'';return `<div class="oversell-warning"><strong>防止超卖提醒</strong><div class="small">这个房间已经填写了其他平台 iCal。请把系统生成的 iCal 链接填到对应平台的导入日历位置。</div><div class="copyline">${location.origin}/feed/${pmsEsc(r.id)}.ics</div></div>`;}
async function addRoom(btn){const p=activeProperty();if(!p)return alert('请先进入一个房源');const room={id:'room'+Date.now(),name:(p.name||'房源')+' 房间'+(propRooms(p.id).length+1),cleaning_fee:80,type:'room',property_id:p.id};const old=btn?btn.textContent:'';if(btn){btn.disabled=true;btn.textContent='添加中...';}rooms.push(room);renderRoomSettings();try{const d=await saveRoom(room.id,null,{rerender:false});if(!d)throw new Error('save room failed');applyServerState(d.state||d);selectedPropertyId=p.id;renderRoomSettings();}catch(e){rooms=rooms.filter(x=>x.id!==room.id);renderRoomSettings();alert('添加房间失败：'+e.message);}finally{if(btn){btn.disabled=false;btn.textContent=old||'添加房间';}}}
async function deleteRoom(id){await deleteRoomUi(id,null);} 
async function deleteRoomUi(id,btn){if(!confirm('确定删除这个房间？'))return;rooms=rooms.filter(x=>x.id!==id);bookings=bookings.filter(x=>x.room_id!==id);await saveState();await loadState();renderCleaner();pmsRenderOwner();applyRoleMode();renderAccountBar();}

function updateCommonAreaField(id,field,value){const a=commonAreas.find(x=>x.id===id);if(!a)return;if(!a.property_id&&selectedPropertyId)a.property_id=selectedPropertyId;a[field]=field==='cleaning_fee'?Number(value||0):value;}
async function saveCommonAreas(btn,msg){const p=activeProperty();if(!p)return alert('请先进入一个房源');const old=btn?btn.textContent:'';if(btn){btn.disabled=true;btn.textContent='保存中...';}try{await saveState();await loadState();selectedPropertyId=p.id;renderCleaner();pmsRenderOwner();applyRoleMode();renderAccountBar();return true;}catch(e){alert('保存公区失败：'+e.message);return null;}finally{if(btn){btn.disabled=false;btn.textContent=old||'保存公区设置';}}}
async function addCommonArea(btn){const p=activeProperty();if(!p)return alert('请先进入一个房源');const a={id:'common'+Date.now(),name:'公区'+(propCommonAreas(p.id).length+1),cleaning_fee:35,type:'common',daily_default:true,property_id:p.id};commonAreas.push(a);renderRoomSettings();const ok=await saveCommonAreas(null);if(!ok){commonAreas=commonAreas.filter(x=>x.id!==a.id);renderRoomSettings();}}
async function deleteCommonArea(id,btn){if(!confirm('确定删除这个公区？'))return;const old=commonAreas.slice();commonAreas=commonAreas.filter(x=>x.id!==id);renderRoomSettings();const ok=await saveCommonAreas(null);if(!ok){commonAreas=old;renderRoomSettings();}}
async function syncPropertyIcal(id,btn){const old=btn?btn.textContent:'';if(btn){btn.disabled=true;btn.textContent='同步中...';}try{const r=await fetch(withKey('/api/sync'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({property_id:id})});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.error||'sync failed');applyServerState(d.state||d);selectedPropertyId=id;renderCleaner();pmsRenderOwner();applyRoleMode();renderAccountBar();}catch(e){alert('同步当前房源 iCal 失败：'+e.message);}finally{if(btn){btn.disabled=false;btn.textContent=old||'同步当前房源 iCal';}}}
async function saveRoomAndSync(id,btn){const saved=await saveRoom(id,null,{rerender:false});if(saved)await syncPropertyIcal((rooms.find(r=>r.id===id)||{}).property_id||selectedPropertyId,btn);}

function renderCleanerPanel(p){const sid=pmsSafeId(p.id);const bs=propertyCleanerBindings(p.id);return `<div class="property-subcard"><h3>保洁绑定</h3><div class="small">保洁注册后把编号发给房东，这里填编号绑定。</div><div class="toolbar" style="margin-top:8px"><input id="cleanerCode_${sid}" placeholder="例如：CLN-1234"><button class="smallbtn primary" onclick="bindPropertyCleaner('${pmsEsc(p.id)}',this)">绑定保洁</button></div>${bs.length?bs.map(x=>`<div class="toolbar" style="margin-top:6px"><span class="badge green">${pmsEsc(cleanerLabel(x.cleaner_code))}</span><button class="smallbtn" onclick="unbindPropertyCleaner('${pmsEsc(p.id)}','${pmsEsc(x.cleaner_code)}',this)">删除绑定</button></div>`).join(''):'<div class="small">这个房源还没有绑定保洁。</div>'}</div>`;}
function renderCommonAreaPanel(p){const as=propCommonAreas(p.id);const rows=as.length?as.map(a=>`<div class="common-area-card"><div><label>公区名称</label><input value="${pmsEsc(a.name||'')}" onchange="updateCommonAreaField('${pmsEsc(a.id)}','name',this.value)"></div><div><label>每日保洁费</label><input type="number" value="${pmsEsc(a.cleaning_fee||0)}" onchange="updateCommonAreaField('${pmsEsc(a.id)}','cleaning_fee',this.value)"></div><button class="smallbtn" onclick="deleteCommonArea('${pmsEsc(a.id)}',this)">删除</button></div>`).join(''):`<div class="empty-panel"><strong>这个房源还没有公区</strong><div style="margin-top:10px"><button class="smallbtn primary" onclick="addCommonArea(this)">添加公区</button></div></div>`;return `<div class="property-subcard"><div class="property-detail-head"><div><h3>公区设置</h3><div class="small">公区属于当前房源，默认每天打扫。</div></div><div class="property-actions"><button class="smallbtn primary" onclick="addCommonArea(this)">添加公区</button><button class="smallbtn" onclick="saveCommonAreas(this)">保存公区设置</button></div></div><div class="common-area-list">${rows}</div></div>`;}
function renderRoomCard(r){return `<div class="room-setting-card"><div class="room-compact-head"><div><label>房间名字</label><input value="${pmsEsc(r.name||'')}" onchange="updateRoomField('${pmsEsc(r.id)}','name',this.value)"></div><div><label>清洁费</label><input type="number" value="${pmsEsc(r.cleaning_fee||0)}" onchange="updateRoomField('${pmsEsc(r.id)}','cleaning_fee',this.value)"></div><button class="smallbtn" onclick="deleteRoomUi('${pmsEsc(r.id)}',this)">删除</button></div><div class="room-ical-primary"><div class="ical-label">Airbnb iCal</div><input class="ical-input" value="${pmsEsc(r.airbnb_ical||'')}" onchange="updateRoomField('${pmsEsc(r.id)}','airbnb_ical',this.value)" placeholder="粘贴 Airbnb 导出的 .ics 链接"></div>${optionalPlatformRows(r)}${oversellWarning(r)}${publicLinksPanel(r)}<div class="room-compact-actions"><button class="smallbtn primary" onclick="saveRoom('${pmsEsc(r.id)}',this)">保存</button><button class="smallbtn" onclick="saveRoomAndSync('${pmsEsc(r.id)}',this)">保存并同步</button><span class="small" id="${roomSaveStatusId(r.id)}">已加载数据库</span></div></div>`;}
function propertyCleanerSummary(id){const bs=propertyCleanerBindings(id);return bs.length?`<div class="property-cleaner-list">${bs.map(x=>`<span class="badge green">${pmsEsc(cleanerLabel(x.cleaner_code))}</span>`).join('')}</div>`:'<div class="property-meta-line">保洁：未绑定</div>';}
function renderPropertyList(){const cards=properties.map(p=>{const editing=!!editingPropertyNames[p.id];const name=editing?`<label>房源名字</label><div class="property-name-edit"><input id="${propertyNameInputId(p.id)}" value="${pmsEsc(p.name||'')}"><button class="smallbtn" onclick="savePropertyName('${pmsEsc(p.id)}',this)">保存名字</button><button class="smallbtn" onclick="cancelPropertyNameEdit('${pmsEsc(p.id)}')">取消</button></div>`:`<div class="property-title-line">${pmsEsc(p.name||p.id)}</div><button class="smallbtn" onclick="editPropertyName('${pmsEsc(p.id)}')">修改名字</button>`;return `<div class="property-card-row"><div>${name}<div class="property-meta-line">${propRooms(p.id).length} 个房间 · ${propCommonAreas(p.id).length} 个公区 · ${propertyCleanerBindings(p.id).length} 个保洁绑定</div>${propertyCleanerSummary(p.id)}</div><div class="property-card-actions"><button type="button" class="smallbtn primary" data-open-property="${pmsEsc(p.id)}" onclick="openPropertyRooms('${pmsEsc(p.id)}')">进入房间设置</button><button class="smallbtn" onclick="deletePropertyUi('${pmsEsc(p.id)}',this)">删除房源</button></div></div>`;}).join('');return `<div class="property-list-page"><div class="property-list-head"><div><h3 style="margin:0">房源列表</h3><div class="small">点进入后管理该房源的房间、公区、iCal 和保洁绑定。</div></div><button class="smallbtn primary" onclick="addProperty()">添加房源</button></div><div class="property-cards">${cards}</div></div>`;}
function renderPropertyDetail(p){const rs=propRooms(p.id);const cards=rs.length?rs.map(renderRoomCard).join(''):`<div class="empty-panel"><strong>这个房源还没有房间</strong><div style="margin-top:10px"><button class="smallbtn primary" onclick="window.addRoom(this)">添加第一个房间</button></div></div>`;const sync=(lastSync?`上次同步：${lastSync}`:'上次同步：未同步')+(syncErrors.length?` · 失败 ${syncErrors.length} 个链接`:'');return `<div class="property-room-shell"><div class="property-detail-head"><div><h2 class="property-room-title">${propertyRoomTitleHtml(p)}</h2><div class="small">${rs.length} 个房间 · ${propCommonAreas(p.id).length} 个公区 · 房源 ID：${pmsEsc(p.id)}</div></div><div class="property-actions"><button class="smallbtn" onclick="backToPropertyList()">返回房源列表</button><button class="smallbtn primary" onclick="syncPropertyIcal('${pmsEsc(p.id)}',this)">同步当前房源 iCal</button><span class="small">${sync}</span></div></div>${renderCleanerPanel(p)}${renderCommonAreaPanel(p)}<div class="property-subcard"><div class="property-detail-head"><div><h3 style="margin:0">房间设置</h3><div class="small">每个房间默认只填 Airbnb iCal；需要其他平台时再展开。</div></div><button class="smallbtn primary" onclick="window.addRoom(this)">添加房间</button></div>${cards}</div></div>`;}
function renderCommonSettings(){const h=document.getElementById('commonSettings');if(h)h.innerHTML='';}
function renderRoomSettings(){if(selectedPropertyId&&!properties.some(p=>p.id===selectedPropertyId))selectedPropertyId='';setupPropertyRoomUi();const h=document.getElementById('roomSettings');if(!h)return;if(!properties.length){h.innerHTML=`<div class="empty-panel"><strong>还没有房源</strong><div style="margin-top:10px"><button class="smallbtn primary" onclick="addProperty()">添加房源</button></div></div>`;return;}const p=activeProperty();h.innerHTML=p?renderPropertyDetail(p):renderPropertyList();}

function renderAdminDashboard(){const el=document.getElementById('owner');if(!el)return;const owners=users.filter(u=>u.role==='owner'), cleaners=users.filter(u=>u.role==='cleaner');el.innerHTML=`<div class="admin-shell"><div class="admin-panel"><h2>系统总览</h2><div class="small">管理员看到全局后台数据，不进入某一个房东的房间管理视角。</div></div><div class="admin-metric-grid"><div class="admin-metric"><div class="small">房东账号</div><div class="num">${owners.length}</div></div><div class="admin-metric"><div class="small">保洁账号</div><div class="num">${cleaners.length}</div></div><div class="admin-metric"><div class="small">房源</div><div class="num">${properties.length}</div></div><div class="admin-metric"><div class="small">房间</div><div class="num">${rooms.length}</div></div></div><div class="admin-panel"><h2>房东 / 房源 / 保洁关系</h2><table class="admin-table"><tr><th>房源</th><th>房间</th><th>公区</th><th>保洁</th></tr>${properties.map(p=>`<tr><td>${pmsEsc(p.name||p.id)}</td><td>${propRooms(p.id).length}</td><td>${propCommonAreas(p.id).length}</td><td>${propertyCleanerBindings(p.id).map(x=>pmsEsc(cleanerLabel(x.cleaner_code))).join('、')||'未绑定'}</td></tr>`).join('')}</table></div></div>`;updatePmsHeaderIdentity();}
function pmsRenderOwner(){if(isAdminUser()){renderAdminDashboard();return;} if(typeof originalRenderOwnerForPms==='function')originalRenderOwnerForPms();else {renderRoomSettings();renderCommonSettings();}}

window.renderOwner=pmsRenderOwner;
window.updatePmsHeaderIdentity=updatePmsHeaderIdentity;
window.renderAccountBar=renderAccountBar;
window.openPropertyRooms=openPropertyRooms;
window.backToPropertyList=backToPropertyList;
window.editPropertyName=editPropertyName;
window.cancelPropertyNameEdit=cancelPropertyNameEdit;
window.addRoom=addRoom;
window.addCommonArea=addCommonArea;
window.deleteCommonArea=deleteCommonArea;

setTimeout(()=>{Object.assign(window,{renderOwner:pmsRenderOwner,updatePmsHeaderIdentity,renderAccountBar,setupPropertyRoomUi,openPropertyRooms,backToPropertyList,savePropertyName,addProperty,deletePropertyUi,addRoom,deleteRoom,deleteRoomUi,saveCommonAreas,addCommonArea,deleteCommonArea,syncPropertyIcal,saveRoomAndSync,renderCommonSettings,renderRoomSettings,renderPropertyList,renderPropertyDetail,renderAdminDashboard});},0);
