from pathlib import Path
import sys

VERSION_NEW = "2026-06-25-platform-lock-display-v1"


def _replace_all(text, replacements):
    changed = False
    for old, new in replacements:
        if old in text:
            text = text.replace(old, new)
            changed = True
    return text, changed


def _apply_pms_hotfix():
    # Run after codex_pms_boot_patch.py has finished. If we patch before that
    # script, its version guard may not recognize the file it is supposed to patch.
    if Path(sys.argv[0] or "").name != "app.py":
        return

    base = Path(__file__).resolve().parent
    app = base / "app.py"
    if not app.exists():
        return

    text = app.read_text(encoding="utf-8")
    changed = False

    version_replacements = [
        ('PMS_PATCH_VERSION = "2026-06-23-direct-ical-sync-v1"', f'PMS_PATCH_VERSION = "{VERSION_NEW}"'),
        ('PMS_PATCH_VERSION = "2026-06-23-room-boot-light-v1"', f'PMS_PATCH_VERSION = "{VERSION_NEW}"'),
        ('PMS_PATCH_VERSION = "2026-06-23-ical-loop-guard-v1"', f'PMS_PATCH_VERSION = "{VERSION_NEW}"'),
        ('PMS_PATCH_VERSION = "2026-06-23-ical-no-external-locks-v1"', f'PMS_PATCH_VERSION = "{VERSION_NEW}"'),
        ('PMS_PATCH_VERSION = "2026-06-24-room-entry-click-v1"', f'PMS_PATCH_VERSION = "{VERSION_NEW}"'),
        ('PMS_PATCH_VERSION = "2026-06-24-sync-direct-v1"', f'PMS_PATCH_VERSION = "{VERSION_NEW}"'),
        ('PMS_PATCH_VERSION = "2026-06-24-firestore-shard-history-v1"', f'PMS_PATCH_VERSION = "{VERSION_NEW}"'),
    ]
    text, did = _replace_all(text, version_replacements)
    changed = changed or did

    external_keys_old = '''_PMS_EXTERNAL_STATE_KEYS = ("icalEventArchive", "mailEvents")'''
    external_keys_new = '''_PMS_EXTERNAL_STATE_KEYS = ("icalEventArchive", "mailEvents", "icalSyncHistory")'''
    if external_keys_old in text:
        text = text.replace(external_keys_old, external_keys_new, 1)
        changed = True

    # External platform manual locks should be visible in PMS, but make_feed must
    # not export imported locks back to Airbnb. That avoids the old self-lock loop.
    skip_external_lock = '''        lock_reason = ical_lock_reason(summary, description, status)
        if lock_reason:
            continue
        stable_id = hashlib.sha1((str(listing_id) + "|" + uid).encode("utf-8")).hexdigest()[:24]'''
    show_external_lock = '''        lock_reason = ical_lock_reason(summary, description, status)
        stable_id = hashlib.sha1((str(listing_id) + "|" + uid).encode("utf-8")).hexdigest()[:24]'''
    if skip_external_lock in text:
        text = text.replace(skip_external_lock, show_external_lock, 1)
        changed = True

    orphan_hook = '''    listing_ids = {item.get("id") for item in listings if item.get("id")}
    previous_counts = {}
'''
    orphan_patch = '''    listing_ids = {item.get("id") for item in listings if item.get("id")}
    state["bookings"] = [
        booking for booking in state.get("bookings", [])
        if not (
            isinstance(booking, dict)
            and booking.get("source") == "ical"
            and booking.get("room_id") in allowed_room_ids
            and booking.get("channel_listing_id")
            and booking.get("channel_listing_id") not in listing_ids
        )
    ]
    previous_counts = {}
'''
    if orphan_hook in text and "channel_listing_id\") not in listing_ids" not in text:
        text = text.replace(orphan_hook, orphan_patch, 1)
        changed = True

    old_feed_guard = '''        if target_channel_id and booking.get("channel_listing_id") == target_channel_id:
            continue
        checkin = booking.get("checkin")'''
    new_feed_guard = '''        if target_channel_id and booking.get("channel_listing_id") == target_channel_id:
            continue
        imported_lock = booking.get("source") == "ical" and (booking.get("is_locked") or booking.get("booking_type") == "lock")
        marker_text = " ".join([
            str(booking.get("external_event_uid") or ""),
            str(booking.get("summary") or ""),
            str(booking.get("lock_reason") or ""),
            str(booking.get("status") or ""),
        ]).lower()
        if imported_lock or "@pms-system" in marker_text or "generated by pms anti-overbooking feed" in marker_text:
            continue
        checkin = booking.get("checkin")'''
    if old_feed_guard in text:
        text = text.replace(old_feed_guard, new_feed_guard, 1)
        changed = True

    if changed:
        app.write_text(text, encoding="utf-8")


try:
    _apply_pms_hotfix()
except Exception:
    pass
